package com.example.domain.model

data class QRDesignTemplate(
    val id: String,
    val nameEn: String,
    val nameFa: String,
    val descriptionEn: String,
    val descriptionFa: String,
    val badge: String,
    val dotStyle: DotStyle,
    val eyeFrameStyle: EyeFrameStyle,
    val eyeInnerStyle: EyeInnerStyle,
    val fgColor: Long,
    val gradientMode: Boolean = false,
    val gradientEndColor: Long = 0xFF1A1A1A,
    val gradientType: GradientType = GradientType.DIAGONAL,
    val bgColor: Long = 0xFFFFFFFF,
    val transparentBg: Boolean = false,
    val errorCorrection: ErrorCorrection = ErrorCorrection.M,
    val margin: Int = 2
) {
    fun applyTo(currentStyle: QRStyle): QRStyle {
        return currentStyle.copy(
            dotStyle = dotStyle,
            eyeFrameStyle = eyeFrameStyle,
            eyeInnerStyle = eyeInnerStyle,
            fgColor = fgColor,
            gradientMode = gradientMode,
            gradientEndColor = gradientEndColor,
            gradientType = gradientType,
            bgColor = bgColor,
            transparentBg = transparentBg,
            errorCorrection = errorCorrection,
            margin = margin,
            activePaletteId = id
        )
    }
}

object QRDesignTemplates {
    val templates = listOf(
        QRDesignTemplate(
            id = "modern_indigo",
            nameEn = "Modern Indigo",
            nameFa = "نیلی مدرن",
            descriptionEn = "Vibrant indigo-to-purple gradient with smooth rounded dots",
            descriptionFa = "شیب رنگی نیلی به بنفش با نقاط گرد و مدرن",
            badge = "POPULAR",
            dotStyle = DotStyle.ROUNDED,
            eyeFrameStyle = EyeFrameStyle.CIRCLE,
            eyeInnerStyle = EyeInnerStyle.DOT,
            fgColor = 0xFF4F46E5,
            gradientMode = true,
            gradientEndColor = 0xFF7C3AED,
            gradientType = GradientType.DIAGONAL,
            bgColor = 0xFFF8FAFC,
            errorCorrection = ErrorCorrection.M
        ),
        QRDesignTemplate(
            id = "cyber_neon",
            nameEn = "Cyber Neon",
            nameFa = "سایبر نئون",
            descriptionEn = "High-contrast electric cyan on deep midnight slate",
            descriptionFa = "فیروزه‌ای درخشان بر بستر تیره نیمه‌شب",
            badge = "DARK MODE",
            dotStyle = DotStyle.SQUARE,
            eyeFrameStyle = EyeFrameStyle.LEAF,
            eyeInnerStyle = EyeInnerStyle.DIAMOND,
            fgColor = 0xFF06B6D4,
            gradientMode = true,
            gradientEndColor = 0xFF0D9488,
            gradientType = GradientType.DIAGONAL,
            bgColor = 0xFF0F172A,
            errorCorrection = ErrorCorrection.Q
        ),
        QRDesignTemplate(
            id = "emerald_pro",
            nameEn = "Emerald Pro",
            nameFa = "زمرد حرفه‌ای",
            descriptionEn = "Clean forest green gradient with rounded geometric frames",
            descriptionFa = "طیف سبز زمردی با فریم‌های چشم گرد و تمیز",
            badge = "BUSINESS",
            dotStyle = DotStyle.ROUNDED,
            eyeFrameStyle = EyeFrameStyle.ROUNDED,
            eyeInnerStyle = EyeInnerStyle.ROUNDED,
            fgColor = 0xFF047857,
            gradientMode = true,
            gradientEndColor = 0xFF10B981,
            gradientType = GradientType.DIAGONAL,
            bgColor = 0xFFF0FDF4,
            errorCorrection = ErrorCorrection.M
        ),
        QRDesignTemplate(
            id = "sunset_blaze",
            nameEn = "Sunset Blaze",
            nameFa = "غروب آتشین",
            descriptionEn = "Warm crimson to rose gradient with playful dot clusters",
            descriptionFa = "شیب رنگی سرخ به صورتی با الگوهای نقطه‌ای",
            badge = "VIBRANT",
            dotStyle = DotStyle.DOTS,
            eyeFrameStyle = EyeFrameStyle.LEAF,
            eyeInnerStyle = EyeInnerStyle.DIAMOND,
            fgColor = 0xFFBE123C,
            gradientMode = true,
            gradientEndColor = 0xFFF43F5E,
            gradientType = GradientType.HORIZONTAL,
            bgColor = 0xFFFFF1F2,
            errorCorrection = ErrorCorrection.M
        ),
        QRDesignTemplate(
            id = "classic_minimal",
            nameEn = "Classic Minimal",
            nameFa = "مینیمال کلاسیک",
            descriptionEn = "Timeless high-contrast black on crisp white background",
            descriptionFa = "مشکی خالص بر روی سفید شفاف با بالاترین خوانایی",
            badge = "ESSENTIAL",
            dotStyle = DotStyle.SQUARE,
            eyeFrameStyle = EyeFrameStyle.SQUARE,
            eyeInnerStyle = EyeInnerStyle.SQUARE,
            fgColor = 0xFF000000,
            gradientMode = false,
            bgColor = 0xFFFFFFFF,
            errorCorrection = ErrorCorrection.M
        ),
        QRDesignTemplate(
            id = "royal_gold",
            nameEn = "Royal Gold",
            nameFa = "طلای سلطنتی",
            descriptionEn = "Sophisticated amber and gold gradient with diamond accents",
            descriptionFa = "ترکیب اشرافی کهربایی و طلایی با الماس‌های درخشان",
            badge = "LUXURY",
            dotStyle = DotStyle.CLASSY,
            eyeFrameStyle = EyeFrameStyle.ROUNDED,
            eyeInnerStyle = EyeInnerStyle.DIAMOND,
            fgColor = 0xFF78350F,
            gradientMode = true,
            gradientEndColor = 0xFFD97706,
            gradientType = GradientType.DIAGONAL,
            bgColor = 0xFFFFFBEB,
            errorCorrection = ErrorCorrection.H
        ),
        QRDesignTemplate(
            id = "midnight_amethyst",
            nameEn = "Midnight Amethyst",
            nameFa = "یاقوت نیمه‌شب",
            descriptionEn = "Mystical deep purple to magenta gradient with circular eyes",
            descriptionFa = "طیف بنفش و ارغوانی عمیق با چشم‌های دایره‌ای",
            badge = "CREATIVE",
            dotStyle = DotStyle.DOTS,
            eyeFrameStyle = EyeFrameStyle.CIRCLE,
            eyeInnerStyle = EyeInnerStyle.DOT,
            fgColor = 0xFF581C87,
            gradientMode = true,
            gradientEndColor = 0xFF9333EA,
            gradientType = GradientType.RADIAL,
            bgColor = 0xFFFAF5FF,
            errorCorrection = ErrorCorrection.Q
        ),
        QRDesignTemplate(
            id = "ocean_breeze",
            nameEn = "Ocean Breeze",
            nameFa = "نسیم اقیانوس",
            descriptionEn = "Refreshing sapphire to cyan gradient for modern tech brands",
            descriptionFa = "آبی دریایی خنک و با طراوت مناسب برندهای فناوری",
            badge = "REFRESHING",
            dotStyle = DotStyle.ROUNDED,
            eyeFrameStyle = EyeFrameStyle.CIRCLE,
            eyeInnerStyle = EyeInnerStyle.DOT,
            fgColor = 0xFF0284C7,
            gradientMode = true,
            gradientEndColor = 0xFF38BDF8,
            gradientType = GradientType.DIAGONAL,
            bgColor = 0xFFF0F9FF,
            errorCorrection = ErrorCorrection.M
        ),
        QRDesignTemplate(
            id = "pitch_dark",
            nameEn = "AMOLED Pitch Dark",
            nameFa = "امولد مشکی خالص",
            descriptionEn = "Crisp pure white pattern on pitch true-black OLED canvas",
            descriptionFa = "طرح سفید شفاف روی پس‌زمینه کاملاً مشکی بدون مصرف باتری",
            badge = "AMOLED",
            dotStyle = DotStyle.SQUARE,
            eyeFrameStyle = EyeFrameStyle.SQUARE,
            eyeInnerStyle = EyeInnerStyle.SQUARE,
            fgColor = 0xFFFFFFFF,
            gradientMode = false,
            bgColor = 0xFF000000,
            errorCorrection = ErrorCorrection.Q
        ),
        QRDesignTemplate(
            id = "classy_mocha",
            nameEn = "Warm Mocha",
            nameFa = "موکای گرم",
            descriptionEn = "Warm espresso and roasted caramel tones for cafes & boutiques",
            descriptionFa = "رنگ‌های گرم اسپرسو و کارامل مناسب کافه‌ها و فروشگاه‌ها",
            badge = "ORGANIC",
            dotStyle = DotStyle.CLASSY,
            eyeFrameStyle = EyeFrameStyle.ROUNDED,
            eyeInnerStyle = EyeInnerStyle.ROUNDED,
            fgColor = 0xFF78350F,
            gradientMode = true,
            gradientEndColor = 0xFFB45309,
            gradientType = GradientType.HORIZONTAL,
            bgColor = 0xFFFDF8F6,
            errorCorrection = ErrorCorrection.M
        )
    )
}
